// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rook/state.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Landscape int32

const (
	Landscape_LANDSCAPE_UNKNOWN   Landscape = 0
	Landscape_LANDSCAPE_PLAINS    Landscape = 1
	Landscape_LANDSCAPE_FOREST    Landscape = 2
	Landscape_LANDSCAPE_MOUNTAINS Landscape = 3
	Landscape_LANDSCAPE_LAKE      Landscape = 4
)

var Landscape_name = map[int32]string{
	0: "LANDSCAPE_UNKNOWN",
	1: "LANDSCAPE_PLAINS",
	2: "LANDSCAPE_FOREST",
	3: "LANDSCAPE_MOUNTAINS",
	4: "LANDSCAPE_LAKE",
}

var Landscape_value = map[string]int32{
	"LANDSCAPE_UNKNOWN":   0,
	"LANDSCAPE_PLAINS":    1,
	"LANDSCAPE_FOREST":    2,
	"LANDSCAPE_MOUNTAINS": 3,
	"LANDSCAPE_LAKE":      4,
}

func (x Landscape) String() string {
	return proto.EnumName(Landscape_name, int32(x))
}

func (Landscape) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5fdb64879681e3ce, []int{0}
}

type Settlement int32

const (
	Settlement_SETTLEMENT_UNKNOWN    Settlement = 0
	Settlement_SETTLEMENT_TOWN       Settlement = 1
	Settlement_SETTLEMENT_CITY       Settlement = 2
	Settlement_SETTLEMENT_CAPITAL    Settlement = 3
	Settlement_SETTLEMENT_LUMBERMILL Settlement = 4
	Settlement_SETTLEMENT_QUARRY     Settlement = 5
	Settlement_SETTLEMENT_FARM       Settlement = 6
	Settlement_SETTLEMENT_ROOK       Settlement = 7
)

var Settlement_name = map[int32]string{
	0: "SETTLEMENT_UNKNOWN",
	1: "SETTLEMENT_TOWN",
	2: "SETTLEMENT_CITY",
	3: "SETTLEMENT_CAPITAL",
	4: "SETTLEMENT_LUMBERMILL",
	5: "SETTLEMENT_QUARRY",
	6: "SETTLEMENT_FARM",
	7: "SETTLEMENT_ROOK",
}

var Settlement_value = map[string]int32{
	"SETTLEMENT_UNKNOWN":    0,
	"SETTLEMENT_TOWN":       1,
	"SETTLEMENT_CITY":       2,
	"SETTLEMENT_CAPITAL":    3,
	"SETTLEMENT_LUMBERMILL": 4,
	"SETTLEMENT_QUARRY":     5,
	"SETTLEMENT_FARM":       6,
	"SETTLEMENT_ROOK":       7,
}

func (x Settlement) String() string {
	return proto.EnumName(Settlement_name, int32(x))
}

func (Settlement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5fdb64879681e3ce, []int{1}
}

type State struct {
	Board   []*Tile             `protobuf:"bytes,1,rep,name=board,proto3" json:"board,omitempty"`
	Players map[string]*Faction `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Step    uint32              `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Width   uint32              `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdb64879681e3ce, []int{0}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_State.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return m.Size()
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetBoard() []*Tile {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *State) GetPlayers() map[string]*Faction {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *State) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *State) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type Tile struct {
	Landscape  Landscape `protobuf:"varint,1,opt,name=landscape,proto3,enum=rook.rook.Landscape" json:"landscape,omitempty"`
	Population uint32    `protobuf:"varint,2,opt,name=population,proto3" json:"population,omitempty"`
	Faction    *Faction  `protobuf:"bytes,3,opt,name=faction,proto3" json:"faction,omitempty"`
}

func (m *Tile) Reset()         { *m = Tile{} }
func (m *Tile) String() string { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()    {}
func (*Tile) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdb64879681e3ce, []int{1}
}
func (m *Tile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tile.Merge(m, src)
}
func (m *Tile) XXX_Size() int {
	return m.Size()
}
func (m *Tile) XXX_DiscardUnknown() {
	xxx_messageInfo_Tile.DiscardUnknown(m)
}

var xxx_messageInfo_Tile proto.InternalMessageInfo

func (m *Tile) GetLandscape() Landscape {
	if m != nil {
		return m.Landscape
	}
	return Landscape_LANDSCAPE_UNKNOWN
}

func (m *Tile) GetPopulation() uint32 {
	if m != nil {
		return m.Population
	}
	return 0
}

func (m *Tile) GetFaction() *Faction {
	if m != nil {
		return m.Faction
	}
	return nil
}

type Faction struct {
	Moniker     string                `protobuf:"bytes,1,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Food        uint32                `protobuf:"varint,2,opt,name=food,proto3" json:"food,omitempty"`
	Wood        uint32                `protobuf:"varint,3,opt,name=wood,proto3" json:"wood,omitempty"`
	Stone       uint32                `protobuf:"varint,4,opt,name=stone,proto3" json:"stone,omitempty"`
	Population  map[uint32]uint32     `protobuf:"bytes,5,rep,name=population,proto3" json:"population,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Settlements map[uint32]Settlement `protobuf:"bytes,6,rep,name=settlements,proto3" json:"settlements,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=rook.rook.Settlement"`
}

func (m *Faction) Reset()         { *m = Faction{} }
func (m *Faction) String() string { return proto.CompactTextString(m) }
func (*Faction) ProtoMessage()    {}
func (*Faction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdb64879681e3ce, []int{2}
}
func (m *Faction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Faction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Faction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Faction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Faction.Merge(m, src)
}
func (m *Faction) XXX_Size() int {
	return m.Size()
}
func (m *Faction) XXX_DiscardUnknown() {
	xxx_messageInfo_Faction.DiscardUnknown(m)
}

var xxx_messageInfo_Faction proto.InternalMessageInfo

func (m *Faction) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *Faction) GetFood() uint32 {
	if m != nil {
		return m.Food
	}
	return 0
}

func (m *Faction) GetWood() uint32 {
	if m != nil {
		return m.Wood
	}
	return 0
}

func (m *Faction) GetStone() uint32 {
	if m != nil {
		return m.Stone
	}
	return 0
}

func (m *Faction) GetPopulation() map[uint32]uint32 {
	if m != nil {
		return m.Population
	}
	return nil
}

func (m *Faction) GetSettlements() map[uint32]Settlement {
	if m != nil {
		return m.Settlements
	}
	return nil
}

func init() {
	proto.RegisterEnum("rook.rook.Landscape", Landscape_name, Landscape_value)
	proto.RegisterEnum("rook.rook.Settlement", Settlement_name, Settlement_value)
	proto.RegisterType((*State)(nil), "rook.rook.State")
	proto.RegisterMapType((map[string]*Faction)(nil), "rook.rook.State.PlayersEntry")
	proto.RegisterType((*Tile)(nil), "rook.rook.Tile")
	proto.RegisterType((*Faction)(nil), "rook.rook.Faction")
	proto.RegisterMapType((map[uint32]uint32)(nil), "rook.rook.Faction.PopulationEntry")
	proto.RegisterMapType((map[uint32]Settlement)(nil), "rook.rook.Faction.SettlementsEntry")
}

func init() { proto.RegisterFile("rook/state.proto", fileDescriptor_5fdb64879681e3ce) }

var fileDescriptor_5fdb64879681e3ce = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xcd, 0xe6, 0x4f, 0xa3, 0x4c, 0x7f, 0x69, 0xf7, 0xb7, 0x4d, 0xc1, 0x44, 0xc2, 0x8a, 0x82,
	0x2a, 0x45, 0x05, 0x39, 0x52, 0x38, 0x80, 0x90, 0x10, 0x72, 0x8b, 0x2b, 0x45, 0x75, 0x9c, 0xb0,
	0x71, 0x84, 0xca, 0x05, 0xb9, 0xc9, 0xb6, 0x8d, 0x9a, 0x64, 0x2d, 0x7b, 0x4b, 0x89, 0xb8, 0x71,
	0xe2, 0xc8, 0x67, 0xe2, 0xc4, 0xb1, 0x47, 0x8e, 0xd0, 0x7e, 0x11, 0xb4, 0xeb, 0xfc, 0xd9, 0x86,
	0x5c, 0x92, 0xd9, 0x37, 0x6f, 0xde, 0xcc, 0xec, 0xb3, 0x16, 0x70, 0xc4, 0xf9, 0x65, 0x3d, 0x16,
	0x81, 0x60, 0x56, 0x18, 0x71, 0xc1, 0x49, 0x41, 0x22, 0x96, 0xfc, 0x29, 0x97, 0xce, 0xf9, 0x39,
	0x57, 0x68, 0x5d, 0x46, 0x09, 0xa1, 0xfa, 0x07, 0x41, 0xae, 0x2b, 0x0b, 0xc8, 0x1e, 0xe4, 0x4e,
	0x79, 0x10, 0x0d, 0x0c, 0x54, 0xc9, 0xd4, 0x36, 0x1b, 0xdb, 0xd6, 0xa2, 0xd4, 0xf2, 0x87, 0x23,
	0x46, 0x93, 0x2c, 0x79, 0x01, 0xf9, 0x70, 0x14, 0x4c, 0x59, 0x14, 0x1b, 0x69, 0x45, 0x7c, 0xac,
	0x11, 0x95, 0x92, 0xd5, 0x49, 0xf2, 0xce, 0x44, 0x44, 0x53, 0x3a, 0x67, 0x13, 0x02, 0xd9, 0x58,
	0xb0, 0xd0, 0xc8, 0x54, 0x50, 0xad, 0x48, 0x55, 0x4c, 0x4a, 0x90, 0xbb, 0x1e, 0x0e, 0xc4, 0x85,
	0x91, 0x55, 0x60, 0x72, 0x28, 0x7b, 0xf0, 0x9f, 0x2e, 0x41, 0x30, 0x64, 0x2e, 0xd9, 0xd4, 0x40,
	0x15, 0x54, 0x2b, 0x50, 0x19, 0x92, 0x1a, 0xe4, 0x3e, 0x05, 0xa3, 0x2b, 0x66, 0xa4, 0x2b, 0xa8,
	0xb6, 0xd9, 0x20, 0xda, 0x08, 0x47, 0x41, 0x5f, 0x0c, 0xf9, 0x84, 0x26, 0x84, 0x57, 0xe9, 0x97,
	0xa8, 0xfa, 0x0d, 0x41, 0x56, 0xae, 0x40, 0x1a, 0x50, 0x18, 0x05, 0x93, 0x41, 0xdc, 0x0f, 0x42,
	0xa6, 0xe4, 0xb6, 0x1a, 0x25, 0xad, 0xd4, 0x9d, 0xe7, 0xe8, 0x92, 0x46, 0x4c, 0x80, 0x90, 0x87,
	0x57, 0xa3, 0x40, 0xaa, 0xaa, 0x7e, 0x45, 0xaa, 0x21, 0xe4, 0x19, 0xe4, 0xcf, 0x92, 0x96, 0x6a,
	0xb3, 0xf5, 0xc3, 0xcc, 0x29, 0xd5, 0xaf, 0x19, 0xc8, 0xcf, 0x40, 0x62, 0x40, 0x7e, 0xcc, 0x27,
	0xc3, 0x4b, 0x16, 0xcd, 0x56, 0x9b, 0x1f, 0xe5, 0x55, 0x9d, 0x71, 0x3e, 0x98, 0x75, 0x53, 0xb1,
	0xc4, 0xae, 0x25, 0x36, 0xbb, 0x3e, 0x19, 0xcb, 0xeb, 0x8b, 0x05, 0x9f, 0xb0, 0xf9, 0xf5, 0xa9,
	0x03, 0x39, 0xb8, 0x37, 0x71, 0x4e, 0x99, 0x54, 0xfd, 0x77, 0x28, 0xab, 0xb3, 0x20, 0x25, 0x4e,
	0xe9, 0x5b, 0x39, 0xb0, 0x19, 0x33, 0x21, 0x46, 0x6c, 0xcc, 0x26, 0x22, 0x36, 0x36, 0x94, 0xc8,
	0x93, 0x35, 0x22, 0xdd, 0x25, 0x2b, 0x51, 0xd1, 0xeb, 0xca, 0xaf, 0x61, 0x7b, 0xa5, 0x8b, 0x6e,
	0x66, 0x31, 0x31, 0xb3, 0xa4, 0x9b, 0x59, 0xd4, 0x8c, 0x2b, 0xf7, 0x00, 0xaf, 0xea, 0xaf, 0xa9,
	0x7f, 0xaa, 0xd7, 0x6f, 0x35, 0x76, 0xf5, 0xef, 0x71, 0x51, 0xad, 0xc9, 0xee, 0x7f, 0x81, 0xc2,
	0xc2, 0x6a, 0xb2, 0x0b, 0xff, 0xbb, 0xb6, 0xf7, 0xb6, 0x7b, 0x68, 0x77, 0x9c, 0x8f, 0x3d, 0xef,
	0xd8, 0x6b, 0xbf, 0xf7, 0x70, 0x8a, 0x94, 0x00, 0x2f, 0xe1, 0x8e, 0x6b, 0x37, 0xbd, 0x2e, 0x46,
	0xf7, 0xd1, 0xa3, 0x36, 0x75, 0xba, 0x3e, 0x4e, 0x93, 0x87, 0xb0, 0xb3, 0x44, 0x5b, 0xed, 0x9e,
	0xe7, 0x2b, 0x7a, 0x86, 0x10, 0xd8, 0x5a, 0x26, 0x5c, 0xfb, 0xd8, 0xc1, 0xd9, 0xfd, 0x1f, 0x08,
	0x60, 0x39, 0x16, 0x79, 0x00, 0xa4, 0xeb, 0xf8, 0xbe, 0xeb, 0xb4, 0x1c, 0xcf, 0xd7, 0xfa, 0xef,
	0xc0, 0xb6, 0x86, 0xfb, 0x12, 0x44, 0x2b, 0xe0, 0x61, 0xd3, 0x3f, 0xc1, 0xe9, 0x15, 0x85, 0x43,
	0xbb, 0xd3, 0xf4, 0x6d, 0x17, 0x67, 0xc8, 0x23, 0xd8, 0xd5, 0x70, 0xb7, 0xd7, 0x3a, 0x70, 0x68,
	0xab, 0xe9, 0xba, 0x38, 0x2b, 0x77, 0xd6, 0x52, 0xef, 0x7a, 0x36, 0xa5, 0x27, 0x38, 0xb7, 0x22,
	0x7f, 0x64, 0xd3, 0x16, 0xde, 0x58, 0x01, 0x69, 0xbb, 0x7d, 0x8c, 0xf3, 0x07, 0x6f, 0x7e, 0xde,
	0x9a, 0xe8, 0xe6, 0xd6, 0x44, 0xbf, 0x6f, 0x4d, 0xf4, 0xfd, 0xce, 0x4c, 0xdd, 0xdc, 0x99, 0xa9,
	0x5f, 0x77, 0x66, 0xea, 0xc3, 0xde, 0xf9, 0x50, 0x5c, 0x5c, 0x9d, 0x5a, 0x7d, 0x3e, 0xae, 0xf7,
	0xc7, 0xd7, 0x81, 0x60, 0x51, 0x5c, 0x57, 0xcf, 0xd2, 0xe7, 0xe4, 0x4f, 0x4c, 0x43, 0x16, 0x9f,
	0x6e, 0xa8, 0xd7, 0xe7, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xf5, 0xc3, 0x83, 0xb2,
	0x04, 0x00, 0x00,
}

func (m *State) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *State) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *State) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Width != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Width))
		i--
		dAtA[i] = 0x20
	}
	if m.Step != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Step))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Players) > 0 {
		for k := range m.Players {
			v := m.Players[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintState(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintState(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintState(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Board) > 0 {
		for iNdEx := len(m.Board) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Board[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Tile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Faction != nil {
		{
			size, err := m.Faction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintState(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Population != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Population))
		i--
		dAtA[i] = 0x10
	}
	if m.Landscape != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Landscape))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Faction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Faction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Faction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Settlements) > 0 {
		for k := range m.Settlements {
			v := m.Settlements[k]
			baseI := i
			i = encodeVarintState(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintState(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintState(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Population) > 0 {
		for k := range m.Population {
			v := m.Population[k]
			baseI := i
			i = encodeVarintState(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintState(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintState(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Stone != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Stone))
		i--
		dAtA[i] = 0x20
	}
	if m.Wood != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Wood))
		i--
		dAtA[i] = 0x18
	}
	if m.Food != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Food))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintState(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *State) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Board) > 0 {
		for _, e := range m.Board {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.Players) > 0 {
		for k, v := range m.Players {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovState(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovState(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovState(uint64(mapEntrySize))
		}
	}
	if m.Step != 0 {
		n += 1 + sovState(uint64(m.Step))
	}
	if m.Width != 0 {
		n += 1 + sovState(uint64(m.Width))
	}
	return n
}

func (m *Tile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Landscape != 0 {
		n += 1 + sovState(uint64(m.Landscape))
	}
	if m.Population != 0 {
		n += 1 + sovState(uint64(m.Population))
	}
	if m.Faction != nil {
		l = m.Faction.Size()
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *Faction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Food != 0 {
		n += 1 + sovState(uint64(m.Food))
	}
	if m.Wood != 0 {
		n += 1 + sovState(uint64(m.Wood))
	}
	if m.Stone != 0 {
		n += 1 + sovState(uint64(m.Stone))
	}
	if len(m.Population) > 0 {
		for k, v := range m.Population {
			_ = k
			_ = v
			mapEntrySize := 1 + sovState(uint64(k)) + 1 + sovState(uint64(v))
			n += mapEntrySize + 1 + sovState(uint64(mapEntrySize))
		}
	}
	if len(m.Settlements) > 0 {
		for k, v := range m.Settlements {
			_ = k
			_ = v
			mapEntrySize := 1 + sovState(uint64(k)) + 1 + sovState(uint64(v))
			n += mapEntrySize + 1 + sovState(uint64(mapEntrySize))
		}
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *State) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: State: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: State: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Board", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Board = append(m.Board, &Tile{})
			if err := m.Board[len(m.Board)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Players", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Players == nil {
				m.Players = make(map[string]*Faction)
			}
			var mapkey string
			var mapvalue *Faction
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthState
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthState
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthState
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthState
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Faction{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipState(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthState
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Players[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Step", wireType)
			}
			m.Step = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Step |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Width", wireType)
			}
			m.Width = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Width |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Landscape", wireType)
			}
			m.Landscape = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Landscape |= Landscape(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Population", wireType)
			}
			m.Population = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Population |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Faction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Faction == nil {
				m.Faction = &Faction{}
			}
			if err := m.Faction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Faction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Faction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Faction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Food", wireType)
			}
			m.Food = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Food |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wood", wireType)
			}
			m.Wood = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Wood |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stone", wireType)
			}
			m.Stone = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stone |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Population", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Population == nil {
				m.Population = make(map[uint32]uint32)
			}
			var mapkey uint32
			var mapvalue uint32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipState(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthState
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Population[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settlements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Settlements == nil {
				m.Settlements = make(map[uint32]Settlement)
			}
			var mapkey uint32
			var mapvalue Settlement
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= Settlement(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipState(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthState
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Settlements[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
